<?


$loopcount = 0;
$data = array();
if ($fh = fopen('input5.txt', 'r')) {
    while (!feof($fh)) {
        $data = fgets($fh);
    }
    fclose($fh);
}
/*

//Test Data
$data = "vDCccZrRzCdmQRrqqQtbBTOvVoMJQHhqMDdVvmYyjlLrKkRBRbBrRrYqQybsDdShHVUsXxlLShHWFETtefFPpsIiSfqQwNWtTwnElEHTtheLCWwZzcVtDdTqQQEeqCcvNneUXcCxUuEeDlgGLdurRjTtcFfpPRrUuHhvVigGVZzGLljJgqQvEUjJRrunNXiIkYyKxzZGgnBfFVGgVvUuIfGgOGyMYyjJmSnNZyvVYHhvVzbQqbnNBMBNlcCLnbmiwWIockKHhqQmMCkKOBwTfsSuhHUFzcCqQTPpteLmMlEZLnNwWVDXxJjdvRuvyYVYwYTuUbBtypPNnWcCgGCcKksSyzZQqYdlkJjKyYvVLIICciiVKkvDiLlzZILIiqQliINvVnNnnNGgjByYbpWwzPpZJUuJbBjjPkKiWqvVeEQIBbigbmMunGgtMmeEtIiowWOunqQnNNUfFTEeSBOznNZoCHhcsvVLsoOSNnlSNnqQyYltTLGJeEjuUkKfnJjNhHqgsSGgGnNRLlrQZzFBNWMqkeEMhWwHEElLedvVDeoHSshJCcUyYKkuUuFfhLDbBLFfldkKEMgGmPbBpdwWGCcgmiIMDSpPgNLkyeEYKlTtBbpPLwWIxEWweXhqQzZWZBsHUuhSdFfDtDdTYyPoOpbUQqXxuzpjJPslRrxHIiQPpqBKkbzZeEhTOonnWwNNtKjILgGlgFfGVTrHCcnNYlEUuepVvPLyhlRrNpPnDhrRHkKCRrZqQzcWHhwvgFfBeEbGcUuCyYBHhbiBJBbLZzlJwWGTtUuZzgZSdDTtsWwDdxXSWwhLlHxXIibRryVkQqIiKJvxXbuhHzZUBVZfFjMmJzjIiGdDLlgyOqQqQYMbdDBqjZzyYJePpeElkKvtTVLEebBXBfPeEzSscCkecvVCEmMKPNyYnpHyYloIePpEgGiLNFoOpUuPfInQqmMBbXxrRnNumCcMUqOoQNUOETtDuqcCQdDolLBXxqZzQwbnCcNcCeEoOMbewWEnFfNMmBTxXyYxFfjJXybIMgMmjJguUQqneEIBbLlQsSqDdeeEhunNUPSspNZoxXnNLjYbByJlOUCBbBxXqeEpxYJjQqQqueEKkUyIiBQHLmMlGpPrRgKekQEuHqcgiIGIiCwsSWWiIzJPmMQqTQDdfFLHOQqoZVDfeEUulLYObOoBHUXqQiIHkRvVrmcEQCcqeXrRiouBbUOMYymTpvYtTyqbBQrQqRmTXgJUuscZzeEjJCzZuGgTNniFQIxmVvEZiIzDSKdqMXDdxmRiiIIrojJYRrRryYIveTiItELwWhHleXxuUXVUEQqBbQTRrtWwQqRrZMmsSJkKjvdDVPWsSLlOGgoILgsSGSXxfsSFwWDLPZTDTmMttPUupZnIiYhwFFfGKkgGcqQXygGZQXxqyWwYWthoOHTCTwWtoyYOZSsEePJjpxXqQsSUTgBqYysPyYpuUSbvVnSsEeGgorRSSTCymMpqvobBjmmMMvdDuKhoOgXxGTVvtKUukzZrruUSsYyFsmpulUtfctTPxXKkvyTtmbMhHmJpxCTxMKkzZMuEnquUrRiIUuiOoIEeoeEYyOBtjfFJTbFyYFVvGFhguWdpyYbBHlszZnNiHttTCeECuTcCtuxcihLifFwWkVcCvIiVpXxPjJvPpeyZRrrRDdRnXXxFuWwURMQVvXxqSWweEIrEzvuHCpUuUqlLQMcgXMDyPlLCeoOEcpDdgSsgVvTtGVvtTGYMmeEVvBuRrkYSsfLlFkKNjgGJnhBbIiHoOBEebBnhHwekyOowWTwWmPoIKkDLJZgoOuxxTfFgBYHdQURMXeIiLPtLlBlLymMYbjbBCwWtxXsgGSqEpPebBERGmmmdQqDMBbMLlkJNnJjpKkkVFfvQmbBpIwXuUNyQPHheUlpPLpQqlCmDRrmqhwrpgLlBbGzSXxIimJdiITtDJfBoZVlUuLCRbCchjtTuUHhJHqGGdDeSsEwbEOcCkKoGhHEehIFfNFDPQqyYpOULlDHsShQzZJUSDUrOweEvIntTfFHHhhmBVUEjOGIjlLQqjJlLmYSTuUmLZsSzDmTtMcXoOSsxXinCwWcNPpGwxgEXxexXBLcWTFfTtNLlyYRnLJNSsJjumNMzZmrlFfLROMrCcOoBUDdunOoopGgMWSmMswoOISsihWIbBBWpXQXxqkNnEPcCpFfUuNeEnenoONgFfGPpSdmXxfzZMeEmghfcgbDiIyNpQOXxWRxOJsYDnNpvnGgEexXEwWRryRYWTRrwdfFQLmTNXqJZnNcCdbBnjriXxNnIuFfUnNRXGgxFNnfEhHFDdfOoeFlbFWpeYyEIFqQfihsqXCcxQoyYqQfyHhmXLJjyOWMDdQBTtbqlWwUHhGgpLlgGpMmyFRidqeSlCVDfnfFzPOYyuNJMcCRezZESoXgycPwWTtoDddnJLlnNLxESrRsbwMSyiqEnFDEcdCBkBmPDOHbBhHhCBzxYSyKdiqBXqVvmsHhSOHDhIZbBHhJtTjVBgGBSnhHNDzZdhZzmIfgCpIiXZrRMKkmjJDEiIRoOrnNkKwgTtGmtTMbBJjWfsSydwQXxJGgjqLlMKSfFtkBleEUPpuwbhppIHwToKkTVLBDXSsqUqtvCCRrNnmRrDxXvCbBFGKOLwWxXCsgcOwWqQypquoOUQEeXbDdkCZzcKNzZnBxfRrUwWuKcTtCkedCmIELleLlQrBisSKkIYyXEWTDdwWhzgGpPoHhOZHSsbBuWwYyyhTdDfFPGZzOoXDszZSemkOGYpLlzNBlsiITgGtlLXQMWrRzfSsEeSsTnYQiHnhlLdgGlxbSpkKPjICKhYwOVvoWykGgKHquUEmfWwwWPHhhZlhLBxhLlQUUtTuiIuWwuiicgcrUHhoOuRbleEjXuiIvsFIibBBcyKCfIcSNFMQqWPEVkKvFWwipuURdjJIfgKsCkZznNDJPSSvjgGJprhUkQdZzgGwFdPpyjJYcjJCDhwTtUmgFfwIUpmpmMPrBShtYfjhpPiMxTSuZPnNpHFHhfQgeEGqQHyRqGKklWwBHxMhHCrRVfcCoFMEekRVyYZbuMmWwXIkuRrUKjJmwBbFpHuUtsCIuHbtThZtcyYUzZxUucCoMwCjWrqQZfWTOobmMEtTuqJjhcCHqQOonZLZztWUrkoOfIkuIxWVEKYykOjpSXIsUzdDZsSOdMmDNFfNgqQuUGQLlqYxolSseEVGgvNnLLlYygDcCwnwsLlFedDWPprRdCDuUJeErQumNPCpUuRrzKkZPKqeFfEVZFfPhusqzyhXSmLlQZoVvOzquXGRoipbQrRqdvRTCKpqRhRWwKojJDvVcEnGkuUKPptlLlLdHWFvGIhHiguLVmJvVjMSkRhwygzZOgGJxcsSpQmMqYnNyPCXyxlXyYcwvXgKkGnDcCsSLUUukKuiFMPCzjEeJZEgFWyfjJbWnNCfFcIoOilyYDXxgluJjOMmuOjJvsSXgFKkfLfpdDPRuMmUdDyYkKrFNnrQNXyYYDRwoxXjJDersDdOvQtRBbuTnJjweMsiPYydxeZZuUFtcYQlLMkjJtzPzuRdCkSjpPtOoTnsYbiRztTwlLPpMPCccCmDjJdPHGOdlLpPfniqKkTtQFdEiptQgGtIwCcWiigGlveUNnhzGgOwEODsIuUHcPIGhqBMHWDddDNmsdLTtiOuUFBdbbNeEgjzdRLwKkvsSvDieJKSsCUrqLllGMnFfPgQTfmQySTNIcCQMcCEtToOpBkwxLTiItgGwStCcOKRsrRSBXPMpzLGDGgdhzsPRWsSNEeMfFmGCOugOhZzzFfcCkWwFfxNeeQqvyPKYwfFmkzDuYymvXuUzZxIhRrHgrcTWojrDXTtooQgsSppTCOocdCDTttuGmhuDnNTpRBbGBDfyIXxwwfwbEeBoBbOLCiRUHhGgunhCCchdOHGNxvVbKMNqfQERrLRrlwgIInXIlbBOEeZhorPLlLFBJjxmzBJOZbBPVhHrYyXnfzrxXfKiIkFGIKkitUuTiIUNbctwWLIildeXucykpEjJdLBcSMlwWRkWwKGzZQYEVmszzZMoKwdOogTkcYoPUZvYyrQClLZdErqBfFICckeEXHhxDCcLlNJCEWweUhVQgGRQoBjHhPFfbWHkgedHEehDLfOHMrthsdHoOFskFfKceEmOwUBbovsqQvvwWVEJmhosPvNnLZWRYjJynmjdXFDfQYJjyLuFdDQwcGHwWcDGmMFHbByrSsRoqMmCHovptTPVHqlSsJJjJRuRxVVRTgZxvVtQlLNFyCQoZoQqSsVSKdqxyzYCkKouehmvckuLXsSRhHrgfmrgXRHBUMmSsuIogZPNEleELTsigyYGRfkGgKpJjPzZFFUufpyYhjJoTtHLXxlhUykcJYnjJNWgFfTIKgImzZSrRNkKmMxJnvNGEIjcBysSJooOGJtCnvpplHFkXPuUdOHuonHfZLrRlzQmxXNkgGKnzGhGTcCtgHHEehVqyOyYocCIetTENFORoOdDYYKeOoEkTCmYoQlxZxZueERxilYsrIstTqBbOoQyUuYTtSOljMvzXEZtqQcbNgGnKVHNKktCNOoJwjSsrNPpwpkcCXHBbxkxXImOrMiwZlfCkbBKQHhEsYqHSmFYyqvzoBEDhTvLlVGgtLeZVvgJXfBLwMLlzZXXEeuOoxIlvigyJtQRTRQwLwWxUOmMokQqVEIDFZzcCflPpVvFmLmLDONywWYngpuRcKBUuhHggSQNDgjXbfvucCxXfvXbcnuUgSTDHbvxyOMvVCLKXYTUutruqPSVyQqYnNvXXeEWweEwvzOWzZRKUxeMWbBmwjJvbQsWbetMIBsBPyhHYyYeEBHOoIiCmVvMLxuMeTTOVzcCGbxvitTVHKuovmzWKzxXvtlhVplDcSeLVvnkfGvYxIbXLInQhHwYnNqUhcrfCsmSbBcCscjIXxGJjehkoOvVkLlTIQNqDtfupiNOWiOoIDdyfvEIiiZGgEqLvXxuETRiIrDhHdoHEHCctkGuUkYnMEeBNNcWwIrRppPMXtvpPVCUwkKJSsfdbZCjDdvVjPlthZLjuNXDdXQqGpEGgepJjgdOmrOQmUiIGMTRrtmTteZZzrRXMQpxXyJOortkkTdDMtcCkDENuUWjxLnEQJEeLnHKoTkKtBpTOtDIiRRBbRJqCoOeEkSllLRXWwxrLEicnNOoCVFhGhkdkPWWysfIPyffFPfeGUVODkdbBJjHhHDvYSfVrRKkTlLZztlnGgWYoGUugOoCPpQGjytJjVvoOrLCeBQJIdQKkrEwLwWxlSbtixDxIsSiMTtuUJdiYhbByYrhwXxgUILpPQqSsTtCzBHDdQdDEeGZEcPxSeYzxKkXqMJZlEjOotEeTWzUFYOZzVmFXrjfvkEyYwjEoehLzZoNUytSTUXwHFbJQqKrRRrbBkWvqoSsqcCshqHHhhQXJxjLDqkKxfzZFPUiNhsJyZMwbBWXuiuoHOgGoSsYczZCZYFifBVvbTtdGgmCSscdWJXEofzZFrwybwLMmfXxpbLgsSLlXEfyvuOoToGgEsfRtKjedxQiWKvkvVUXCkKCtnufFdNWCBsdRZyedGVPJMBfoETijmjUVlnwpPzzsbHFTFsJTNngXCgRrNyvGUQhVuHyUgGwCcwcYlPhMmHtYwJBmViYGEBbjjpeEokKJRQOmPcugPDdpGUmhzYGgyOeSIhDcrkHhLWwlPOmCcFfjPpJMxnYRclfYbOgFWXFiyyYOHsymLGNkKnsqPBhHqegWwfPuWSlqULVsLlUGnMuzlLYmOjllLLTPjWsjFppksRrSKhdyfdQZpvjyrOvYyVnmHOFfPpkykWUJEgGsGjseLlkQEKCLIoOtXXxcmGzXRptCGSyMexuZFNSDKDxLlXdpjmsQqryvhwFxsGXoyJjcPZqKNjIcrUiwIVviWOoNjjsSJHjWwyVbFLiutRPpBKcChPgDdGRuhPpHeEUpKbZBtFHdoErkKReZvVpByJgONsnCwTGlMcCkwiuOJfHQGtTCwzUkxgmPZlcxirQDjgGumjJFMRWclOnnrgPeEZCnEzMBdmiGhzKewZOeYPmiIHYsXKsCcdNjtygiMmIMjzYILlSkGgkKKVUfEIbRrtfriLlIRxtybCoIuJEwEoqBoTUmMuDsPpSdfTZeEztqVrqVzioOFfIdVvDyDxNYurfSIJjrTtzkIDCJjJsUBFpZuJfqiLCclcDdkJTqPvlLVYfqebgfFeEGRHwxyobrWwRzRxNeEzptwKkWHmZbjgihkKRgGocbwqJwWjQvKIqINDChJjHpXqDnoUREwWhNKMlPjfFFdBCcbHhVlLLCCMfXxIGBwoTkPOwnpPwhtljQjJdyCjqYrHhsnyQJkeEOTtXiCclDkBbuOZovTXikRsGWxmlqrLKxLWgDmREuUGzELwTkUuPEBLSItHLpPLMXUtVvPzEkqhHQVyQdBTVmkKElihTNPTrpNKJjWwkEYZsSzvusRBjSFkmHhtxoOXgsUsSWgqjYKVeVIFgrHXDSdwqQcylLlsbYycfFCfJNLOPwnQDVwUBzZbYleGkusyfSEorRzQVpJMnNVxdZPdZbBzfViJOvJcLckkwIifFQYkBTpmZzSTQIbQOHuUpPKkFrRfGMOHFDbBdIifhobGFfXxTBwyYWbDhHdjLKEwSgvBSWwxXUbQeECWiiIIwikeRMuXxUXedCcyKkUumDdjdDGEjQpNLhpgjqmdoxoKgCnvYgxzyWwYXTDMmdtVNmIkKXqRKghfVzHEMMhDdQuURGzhYypJWgqzLVJGQyYzrRKIHhslLRuYPNkWXHyZkkUjJkXIZxrsFsntTNjedlYyzedsPrbFfsvBJnRpCQdDhBbKkpftTlrfEZrGULOoiIlWhpyPtBzZUNtYJrigGQtmIigXuUjUZzdBrXCKYHcHHJueoUPpuOEUueZrvjJVGJVLSPmVgHUcyVJXHwYqmVPZtfUIBNmckUuEwmnFSOxuDbBdUZXQPkdPHnnkvdcPljRpINqsGjqeRkYoxghHpLRyVUDoRzcYkUwslznyEDnLXLrgOKryvKIbeOwBldUpbTDoTQOhIinDDLTmcbRtlOUPXDJGkoQbjsRYIiynMTUJKbQcZxIiXRzkKvLqFVGifnvvGzQRwvmSDuFqQfRIpEhDdHBHGNshHrxnEKDXwzpYrHqTkSsKtiuUIEcORpnFhMPsuiESKfblweEbYTkInWXsxfFeVHzsQHLpJpbmrNlCVkOGYebQqeoOwgYqiIQCsKuvsUzMvuWzywCHjZIuyMbEBEGPDHyDdbBffFqsdDJjwmctTrjgYhGHWElDCmOQPgiKnvQSSfmlNuNwRbJJKFlPSiyqHPphtcCQYfswnMwulXpQfCSFNPHzZVvhcKkkeIoXipdIvfFVgvjJEtIhhHJkuPodEprLJYgSUIYyEMppTCZIVntgFlUuckmLxuopBDEHrkKnOoJoWbRGLeTVYqQMHvGwpmPpTBEJIsNnlfQCDvLHeitnrrRniVJtUnrxXwhHBCMZXoZCInWoYjtbzShYZMtJeUjDdqxUmjldDLJgCINTLFhwlZzfxwwCFnqhnMcCdeXxEDmKkPQJdDRxkNoquuLgKOLvkZIRyixXXTXIFUclExOUOoudkpPywHCcoomzZMMuTwCUXwoboDElbJfQpWbzZBGhIZEgSsBGLJhxmiOsFOxXWdUlGBFgXtDrPzgGetTqzdFtbqKNGjOCuQcsFgoCfPHWhksuUEPMFDHhSwImHWBbuomURfEHoRwgGKkyvVQZgLXEVLLixYCkXthnciBewXvoHZieVKrKoYNOzPyCXiIkQKwITvLlwGNdoSmWUwZUGvVgMXmLBDgmlFXxItotVVocPzrXCLSDNwipirZRxZEHfYIUuiMNlJRrjtWICvVQKPHVfiIBhzhOdIpgCcXQHUTtRndWMwVOwbQWbDRbGkGwWqJjDZvswukGIxsTwWLwXjxUyHhNnfCJpsPiRGrRZjJOOSsCxZJIDnNQVbSUVfBrQJHhPgGEVrrIdSWfVdJlLcFEJJHgLnuNmUFtDhrGXjXxpKkNhmgSwSJJqQjBwWZRrUjOhHEqkYLlEZXwmmCiNzZBcSYIhvSHTcnULkbWCyEfGVhnrXoOmNIrxdYskYotHiENBmpiOontYygqQGRQSZwsIYJjkKfWwmMXJBSHXlzulRHtgSHqbElOjRPeEsxwmrUlvOGMiIRHvVzvlLkoXumMUYyPMyyYcCOoCccCBxPZzRrXkUdoOlCsWNFJmqyIJkQBgGpPdFwgbtZqOhiClbBRwWbfuNTMsrinLEkEehRbYvfrfUycODMQsnVvuFLeNijDJppcLlOsVMrIMGcHTvVthcWKdCtwBhbZbPweEWFHLvFPFmRxDXZzqizYyZwYyOzNBssLkregZYcyYXBdtJmSqUVlVzOdDRRJjrQQcCRuCKkXUjFcXVKkoEbLpHnHMVXlopoFFjgsjzXXNfwDlFtWXqPpGEJtPiKeqsyYYZuwKwBoLpzWqKoOYEYSqhcwfPhElTgjkiGQbnrKepJlfLFzzxInSqQIcxXVEtYOoeDjwMtBnOhTqsVcbSMiMIkZSMJUGelyCjJsrXYyzPHYBvQBHThLxXvgkByYbopCtnSyCiGCbpqrdDREJRulLtoOrZjljNnmHKkubQlqpFmqvFWldpoOPSrYCJJhLqJzWZZSOYywehmQnoVZzGusgIXrgxeEleBbEekRDWFfwSsCzNswDjegGfyVxlbfFuGgoWJPuENqoFfXJuUjMPpwcfYJeuUEWswWzCxflLLiutunCXtuIowlmWkeBZIiRZeRrJxhLTtdHvubBSZHDNvdOohUirRFhOJhOcuJdXwBQpbZrOgXjiWjJsooYSiQpLxVMysQyZNCBHYpPNSUgWjgLtytINkspknvUEUqFJohpzrOSsNUVfPJQeTxgkNSOhffwWBJQbzFtUfiWgirXgGbPdrrbEwnfiNwKSfDoIJjkWcRnjqbHhLbqpOfNjOPpxjsGrUYejngFtSybTdrXCpsqbKJkCXhMoOmHGtdSphfGcGNgGOFZLCQxcqTXxzhlSFMlLUcDrSgEVlThHtfPYTfjofkVubnBYdQJdYzSQxgzNEgMzHihVuUnsCwxcgKimmWwdbBIHDdTmzxCMFcCNfyKoXEvVeXkHwddORLlOYoiwkTwZzWZMlBLyowsSttxESWvfuEQJORGuTthlGtoRrOTDVuJiQhWiIjGrRPyfciGgteRrENGttGMgGJiEZJBukFsxTnFWFmpIVvDXhnmSyYtyJxIzYZXzXyohFrkbVJXzZeudLeEKKYUClxQqseJqQmzfnywgPTFJcrkKBnnrrlLvheRiRLYlEqTIkWJSKJktBnGdrlIRHerYVyyYYxGZVIYPBbJVGHKgiJgdvXUNHcxbIsoeSrHrNsdvCsSGnECuEVECCJjqzhqLlkMbmcLlCGqBQZhyYHpTFQJPhstkgWcZzgkqQrYFzqzYXhdkKDWqFIXcCxiFpkMBMSXmVxVKDBxcPYTupZDIopJjpXWKHLSKxTymcCtvSmVIGiuDdSVjQgHuOMeRopINJjMDMFnwFxZCQrclksTbmIhiCXxxBllSQKfBbzWGOpEGYuQPukgNEQqeVPkvetyWpOGLoumJjBVSgGrQHLOoIVNuQCzJuFcfwyDNrihVULNYfpEMvWwFmgdWPvlYWpGYZYUEdyYrSujTQCUBbhUuCKGChgJpMxwzFePrneOrlFOfRschEpPXSknfKEBKKRyKgtjqQsWFfPxEXxevVRFiYyIWsJQqGdUYITySsTfXkWwNCYyjOFjjJZkcTdjpLfGxHxDhQJHLbkUOdESMDsWtIGvVBydMIWNRdPvneMdtFFSJCghQqlbLyWMkeEVFRByNuUCrqMOchkyFtiOtIHpELWKCCODyWdCNQoUyXZrIiZKOnzhOiOQsuYrWUuzVPtWogpFqpXbkvOgZgJIVkLKWJOrmLUYFTTJJgRVPyoMllkBtuGnzbZmtINrNHHwBiCookfURrpPgSdQspPisPYHJSnuEtSLwjmmlXSzbPQScWqfNZJyqgQFYDIKkocmjkdhoEIQSSqvpgbnNJSPsCMDkRvPjpzyiJGVmuUFfvVGmHyNOUZusitOXBFUtdWwVVJhUTCCpXHxBDybGcelhEVyuhJiFSDQunpIWwWnqlRWtBbushnyTTLBbOYeVQlfYklSCSsczFxxJjyUznwSWWbvIopPrJYsStGgcgDpdsfFSDPXMmxdGChHTyjROiVBwHNnhwsWNZuYXXfZsLnNKyFLqvEyoIilXLlxttYNHSUTwrLQNSswiPNUqdsfIjHUYveHLECgBYdMqQmbvFfVXhxPcctuHjvvDTufbxoTISUzuonYhMgMvgjIYZPJpVrKbBdmCccSpsjBGPVQssqieOHDKJMCOidzZyfqGQYjznFQwcCCsqpBZsxLMMJhHWlsTeUNsjhypSISqDsGuFZzKOOcIbWhhkKnRniTMzBZNgUTbRrKLLmiIOYpvrGjjttfyulMRojwklKvijGzGoVKBxPQfPGOwTpvZwRyUSqoIoHZNgnNGotTkzRzxYvVuOqncDwYdocckwlePhiToITfYKHtTCoeEmQRcNnnYbrfvKmwYlBZzLHGcSsjsffTDmENVpDrnwimDYbgiTwSdmsOrdDRoerRDDBbdouKBlhjqHdXhCcXgFlPJDtCKzjlLJJfoJmMcnKxFtYtiyuDgjSwfrXphHqQwSJTGGfFgkyYYruUkhHkbekFNLllLnOoNKsxeHCSrFofrRLRoENRpEfZsSWXiImPjGHNncgkcHucqtJUsRDeuyzygPwyLVpwDGMfEevVWwUuVmePFynluvHIRndYWFCGgfUjlLZcqUnvilhqRsvbMSsUOlgoPcCwYTEVKpvnGKUpqdpPDUygePogwZFkqsLLbXcIHiMBtSKLCRqczXfWNfmdmJjniPOrEmdDoUhGqJvsUIgzzZZivMsVTVvMYtXzHhZkslIihkwxPPOidzPUtypCXbdkvXvMxsmbmCcKPfIJjifQivVIwHxyZQZfyRKGCwGwSsWKTSeEHpjqftPzNnqbQgMBmKQHZQmMccevjNnJeUceMMmmNgxXcVDSnRhbBRsEOSiBXChnuxVDGjIGkhgvjpyivrRzgXvyREhriLRDgNbTKjksjwKittMmTQeLylrIrEHLlVRRNNbLlRCjftDdpGWYNFZMjESXLcuykklDUExjvtODdhHoTBKRfHOYxZxzyZiXjYTsqFwWfQMNHxdiPMfwfNtXSfKUbjzeIjBbmCqEgGeQcgvVTTgnTICFYpgJwHqIjUvdgLHrRUCcgrojqeUFVwseZzXTTsSWOYlbLmzuUtKBTtbWIOyorUuoDDWhKxHhxOkYFnfmcXZMtPOophiDMMIVvkGCXWcSNvHIhZmGenZGXqsZyDjqDybNBUvKFOJFtyvXxVxbBXpFLvoOeGSssRdCumfsLHZIitDdQTtCXqclzfongCgFHPsDKCckTgxzZcKjkBQSPcxRDtBYsTfGNCcJEyuRgSJXoJnFoPQBlBQJNrCwKiOdFskWnIFNWeBRRDpBxRIGwIFuTfZBqjbFFHosnKGXtEqKLlkjSspFvunVvoRZPHGgOjfQueuVNKPSKniTYTlGJwGusnyhbcnCcKkzYqSYmvXlPQqnNqIsyOOSwIJxGoRzBPqbWxDjUepPECoHjoHfIuHDVndhKkzsUVhDSslHXjEzrzbEKwMeELCcWOiUyYTxcgGNUTUIlFXcnNZSwfFjyFCCJjcWmxxXOQnYyeUbBpjwOUBQqLXvYFEJdWSnZcdrKlLELXGRKkxiGSUgxnNXvONqMHEWoPpYyszzwZjQlHjjcyRsRpPrDLwfVQMfPQLqBUhMFfJLJzRTJjsSFfUrjeCcQPBcgIcYsNTcPOKGVxXlHthbqVbyhpZxRJHhjSjJcYLEgujmszKimImsBCvSQLltHoNbTmWJdEyTevjJCisNiXZZflNnVvFLjPEkRNBqgIKJGtLeHpFWCHQsmbBMyeyQqkQwZPlObWkuopPOUWUJjzySQEkIpTjXoOxegQxwTfkKLdWFnxxZJSTtGJffOPOLxvmhNhTtPlBeXBbxOvxCfJuxcjJDwWdUrqqFfroZvOoLvuQsMGgjTDbxwWCyzGERKlSUuSbBowWObnZoUuWIQxdXrMfpfVlhfKkpBzBHbWTclRrLDPEepkpPwCCgmiRmvSoCPPjdJInElfUNSqmdoCYuFRFVyBrHKelNIRSmtnUFBrLcIHoQzTBrRGWfDbqKjiIiYQMjfnwSMmcLHdDhDuKxUupXbYmUujJpEeYyxOKVZdDhrmgoVLuRMWXSprJoiILKkeCCmMccBQhsGThrLUZLxhsbjxFyiSWzsDdqrTNIPMbneIhTOyKSyFfDXRcCinMxqQRNHvgFeYcwBKluNCthsVHiysCbnIcMMWxzeyKQeoBbJuCcpcCPuUzbjsWsGMHnPJxgRHdTfuZzMnUNlGhjjefCjDvFwsDiRRvepjqRbFvusbBBvqdijzXcoozgrIpSPjcPpFYuBbXJxWltSXigKUWSVzdQgKgBrdBwqBWovWmwDSsNruhqxGPiDoHZHbKkFvhpuUkqciwTLnmyFhezXtdyuRrUYDmMTrzRIzZPIWsSndsFPlLpflcxRZpCOEPpedkQqKDvcZzCvTOTifLMGdblMxmuwWzWuwMsODoYyOsSnZiIzgWVtiWkBbqKgGxcYpZonyOkRkvEIzhOVxWoOEbICNHTxKcyXIllRrvexlGzqYWIiwWrOheFruMOUwhMiWskKymMYdeDYCrRcydEfmpPpeSKEehHHHgGhwhpFIicOGfSCqUcoJgnkQBTfDZQbBEZpRdTxGfbgLuDwofSqQoIMXDdHjlgbbeEBGeziHgbBwPqFjBLedOBOWxucWtUmodDpPOXxOOhWYKDoXexXpPLCufixtxqQtTIJjYriVvzKVlokGlUUQOZznKDdtTXSsrjqpNHQNfcWWXFLWHfltVPpvnicGMuXQJuEjTmzyHsZBtUuTTJyOwNVviczOxzQqmmuUMcbJjWRNuRrTjvINRNTIEhlVdcqFLCcSijebNntvZzVMPWgVhmyvtElgnNrBwOjNRhedbsSPOBJGgjbUXlMKCmMLfGTNvizctPPmeqQiusGyjlRPeeEDOpUKjhHHiTeVGiDPIxOiEKCpJWwjnfTtsHBbhcFqPxLjJUWmXxNWSFyqsmMSTNnpPQYIspLfkjoOjBrWnUnLMFssqVNkIGpqoMcdLewhgHjJyGJRCMWQqSQFlLYhdpgebeBmYUizJhcWYZwsSUVmZuSVUkScTtyGWEBEygoKvcLZznRMBPjPlhvVqSsSZhvmqKkQMEdzZWwfFDXSxwNiKtyBbBWLBFkseIUSpmHfNProCeQhRyPZWxsSdkeNXRSnrRghbpdDPePirUdsMVWrqZUEeuTtgVVNFIgvfQgyZzYkKGlVnNZrzCLlzUuZlLqBkjutmNrSJBqOzZKgjdxpWwuoLTrBCMtcrRClsSddNHoqtOdtBPuDLbWoEBikVYHhRkoXxGRlxlNdeYNZLSWuKyCZrOduvYrlPGXOyKrEQJgSQniPrJLpCDVKNNhpDKpqxzXosfNMWnNeKCMnXxbiRruFTzpvMQHhyWhxjvYCuhGvMpslvjVvgRzEUjhhXxqQChykcxRbDuJxGMTqIRjyTnubTpYPHwugRzeFRLFPHWwqcPrNjbVSBRpSDEZLDEJSfSRXzixKuIOoiKKzYhxwKnpyUrSikZqgjvlZQGwjPHZgruUqHmmehZWwvFLlHGkrQxiMnvxiGgIZXGyVNcGkOXODMOoQJGPHlnPqJegJlLMYpPDExmrERrKIcqBusbVGnNsWeklJtgBmgsgGShoqBiqtsMPtHhbKyqJjjJWyYKKClCjVcCojIvFDpzDXvKoGGggOkmjNnPvqZxbcCBXOesFkKYSUVvKgELyuWvdqNWyYpolnZzjFYyBSLYNBbnCWDsdxhRGfivEvkyJQGwuSGTMKfshHJbrSUVyenPRtpntHILzZekKMvtbDqXjJJjxYvKeRcCrZpTuxmllhTislbepKtKkWleZgerLlMdGwlXclLCklRzZQLMXRrwgSrKxXIxtVOzoUKdLIxosSKjqYNSRyQJcYDqJLTHWCcNWopKtOHhWbgiFmkKccqQlvCmMcDfJpLmknHeruONdQxPcdGgRoOrBbniQvvjJVVikVWByfFYCOrHIGJEeBzMhTbBPoOZnXrZBOYoIiOqQXJjWhrBEQFdDypQtjKCIQFjUzPUufbuSjBbcdiKrRZRisFRUyRrnXdYZvQRvQTteEFUxXutObQOeWlLWwejUEYyetTiOLlcBYKkTXFTBGgieFuvsiyZZzJmGYTJnDSkxSyhMpyEozWEkZHgIMDQqbmZeNhuUHRrczpGRNNoLCwrmfMUgGJsSdqRIXCLzpMXcCKuZKkgGWcgqUuhFjpPoUIWKmLgeEtWwFfWcNSnoGjYbPzGgODhfTbzBkPrpHkbrTUIBZeZzmMEPGgpzblfIiBvYJhiOoITxQqXtJnIuRCiJvVnkQzpCYOxgSXfWHVYRSMJPkdsnfzUXEmYsgcTPrxZgMCxTilVvckSseqKEYySJgSejuIiwKYKocbBCjJhMNXxoRYJVPIizqDOvVoFYDHwWPPfJSwJptMmJoMyZUmNguSvluQLswUpFGEQLlbpQSglMYnNShoYIfxwfGoByFLXwLlWxCryNXiIzZmMopKRCdHisEoZHMTtRruUCvVpMoqrjOXxPTtJJeSsgyICcvdDkuUKMbjWyTpLuXyYgGxUyCWWuYzZhUvHqugVYnGcxGtjSftfhBSZZWNLvuJMJIPpHhteOyYFbYymlfeEFLjpvgDEYzrDSbZzcbBoWwOwnDEeUNTccxuKVkweEIqXDEJBbkTrFSeOteEUVSPpsYFexGwLloKkOWRbiIBrlBPFlWBYWROdDexjwDVvMDFIfyzyhOUIUxmzYjSHnIupXQdlJXjxHGgPpSSsQSsOUuQVwjBfhWxEBbepPutsTYunOlHEOeJWeKVFJRxfMvoBbHuUhhHyfuZwJeLzjkKUvVumQZyEsXpCezgvCcFlSsLfVqhbZcliuGWHrRRHyIDjmXdXVvITBsLiIXlWeRKlLkqDijqbEclRTYJgqcxmMXOywNVNuUnvLBbpPfFoOvFsyVdhIeEzZiCYycDKdOmMoXuUxIiovGgugEFpEVQqveFYpiFSYwwpKDKHgHfQqvIeeuuJjUUEyYRrsKvVcQjrrrdTxXoebBEtPbOkhNljqeNYylXJwHQqhSsIinedKTmtKKTRjYPqmxeEzEguMqoRMoDGPWwUuPgxxnUJlzHTLplLJJczBDFPpKqQkjWueEZVRrvzxXcTxmPrRiCnnbmNGgyKgKTgGhehOteUVlQezIeVFYwonREerIPKkUFTdQiEeInqitvVKKHEgiJCSWwkKsMSDCcdcFRpPCHuQMmyWSsqNilxBiXyBbVgPpFKNlEsCdLyYPvHLTjZzJVPpZkwZMVOBbIiUkhvIVwWXOUuoTtuUBZvottEcCmUXYWDdwylQqchbQqpbSeEbimTEBwSqGgBVXxWMTNYyntVvwmEXuZzkrHhFfwoZVLlWxxVvsjJpQURyxklcmoYXVBhNEewWndtsGNCBxVFbBUVFBxJSsGdnqsGGbkCrUgGPGodHTthldDMlMftTeEBbLdkKievKuXMmlWqrtrqTjpPYGIVLiXtCcTUxxWwmWlbFxjGzElHdIiebOZVQYKkyTtfMshQySeqcFLNnEezWImRoMiKXhxKPWnRJWjnzZcTnhvkBIiCTzexZVmfFJLoiRSyLIXrUzXzXLqOyMcpPJKkjbQqBtKiIkyyfFrofnrRiYQvqKkQuWwUgZbBMiIqFhjJNbdDBOUtThoDpxKnNfhLPPVNcThHjgOjYbCJixYyXegnwcCWVNPpjXnvVJjsMiMmGkiMmtGwyjCKYuOSsHPrIStenpzGOibhrxGRMFGRdDrxlUxHhXKCVMHoOEUOJFfjcyZYmMXdDQDksvOzKZzkOqcXxYDdfnqTXRrzGtrvvXrUrsSjjLZzqQPpQIiRKkJjrhOhcQOYOohfcCiIYipPIygdChgCpPWqzNnMiImZfUlqFdfxDJMNrwzlwWJjVpSOnNHMjeVSVOuWKksSoMCSfhDBbIiBbSHTIiKkRmhoFlEMmGKhwBpJbOqYyrqvHuVvclLjnHhdKibtNJjBKbnTQyOoYReDzcqRVzupeEOyCKtGjJlLDWkOmZSMveyqgnwWGgNrLEemsCbKgGulLUklDegSwKkZSsgGIiWoOwzWsEeGPmMKoOYZzClLUxEmMXxDfFTCBnuKkgoORZFNxRvEFfepzwWojbUuZMWeEwXbDkKdfldDpROHyYzoLidDxNiiGWeqPpFQnmkBIigGCMmgXxGcXngKkhoDHvVNndDcHNrIcdwWDlyYWFWWiEeYFVyYvfFdHhbgMFfmrPtdUHCcMgUTOodcDCctPPGqOOTSstxdRJOwtGLlgCRGGgcCibmMBqQVMUlLdYyZKMUuWykpYPpVEEnXxXKZHoGUocUuguUnwGgdDryeEYpIZziSZHglYyZvVPdDWwmpxbrkoTsWlXWKbPJjemqintcCsYqMFtqGeEpNmgwWNYeEyzZnLVvRrZzQrRRDRrdQZgGzqUuuckjEIdVVWlrDZJGncCBBDbjJfocCIlDSMniIwhmMmbQHgiSspCkiIKCFfchirRKMkKmkSdoeWoxXZHjJuEVDdLxXXxITqTPIeHhDWYywfINFDoghpPpHhMpLlmWZrIBySNJdDsKiIlLSscDrUZpZQqTKmMCcmqyMlcCLmCTfzHhzNXbBxnEXDpYyISmEWhtTHNtUzIiZrTqVoSREdOWrtTdQKkqETbBtfFeyxnTTttqReElGxVomMUoULQqGdLwBFYwfGecpnNmfFfiIIeEldJjNxVWIYyiCTtHhxoOLXYjJbBjtTcCoGmOonnuUNNMYnNWHqQrhHKJjsvlUIpPiVfwhDTgNeCnNdOkrHrQPkctrVDBPGgIOrWcCwqQgxUPLpPlpGgMsxHtTYZQSUHpzvQkeEmMcpSCcsfBbFcCnxXMUqcCRjlLdHvVhHhYycDwdWwDLFfqQlEfSWNWdGljJIcCiVtTvkKLOXynnouXxHpPhSixskKJjlLsSPJoKkevwLlXiUyYKiFKRuwTlzNQUewWBtwFtTzRwlLJZzcWmOXuuUCTRrzgWwGHLlBhUicSThPfYytTWDkKdMixQsSqSRrsUBzYgGyvrKmfRrOGJjgjJFviIvVcmXCchyYbLNngQrXOocCxYhFfqhzdLmMKklDUggGWwGscCtXKkTtmIHuUJFyTOoHsbRMcRrClLPuoOiWnNGLgGlMNnuWHGLlgfWDqKuEeHRWwPVsspjdZzrRKcSkGFiDromqQMxXOPIdDfepwmQqfnsCiFckDdGEVvegYCbfSVUxJLBhPpHCGCIIUUuqpzZQYEeyqUuhHPHvVXeEvVGVvgbgGIgGilHLzmMXxVvHLlpFMCXxceQkBbciJlHhtTLscCBXLsbBSnNDHNUfyYFuhTtIqyKkNFfMmtFHhZwmqZzxSLbUuZzPpnZPyfFJUujgsSoKRrMEdCcDdgGxgptXxHYUnNNntwexSjJsbRdDqiMtTcDEFbgGBmMPYDdoCGSclweEWTFGgftIioJPpjkgXsSkKxfcVdKrRkMccTtVTQWwuQxdbKklvDWwdtOtOOWwooiIbBWhiMmPPHPpBwWWLbKTYmMysnNkmWDYVvFedzxPeEcGFdDiMHrRTtsbbvziHdhotEeLlTKkMQxJjXxbQIvVDDdMmkkKYsyXZbcodpMbKbcDCePpHVvhdfNeBbHhQdDIYsmWBeXlwVvWjNDOxXpCYeyYEGxnlLNOsrLlmVvjntTUoJMxXJQqjmcCjpYzZyZbBNFjJiIdvcLsJjEQDHhIdDrCcfYNnmMPRGgrPeELlIUuioOujbBJLmwoYlQqxlNpPnLEeMoOmMYBbFOSHPwfBLffFUOoceRrECbBxXYyuJNtfFTDzKOowRrWWwkjQxCcoORrntMlqQlLqpPtTDWtdDhHcEdDeCBbwyrYeGgEeNvVVPdzZySjoXKkrwXxoqJjPJwWKkjnYdBGCFfFHGNnFMDQqsOoiHhIKTQkvVKqtxPwbiwHmPOWwNbRmlJjLonnNMUnjlNrqpPQnykKYkKtoOwClbGXWgIIIhHiixCOoOodzZlSiIsGgMtXvVxsyNeEnMdDMmJtPpTiPwWplrRLgoJeYyqQuvbMIOpvVPoiNfRfFrFicCPpVeEWoeVvuUERudsudDRTxEeXtrkKZzjqduoMmdfniHrIiRtTiIgzZeBWuUgWwtsSTgZerREzQBRrHXvVOokseESYyKxhOEeorcvzObFjjMwwWWZzsbBZPRWHQMmFfMdMgGuLdDuUlUcLPuEpqYnxWiPYyGgMXXxxqKQcCqgGPjKMgrMJMmSsjmVtTveQTcJTplFfExbiUuIYyBmdDMmWsEeSwrbVvlLBEeuyGwWgzZDgGdYqDhypPbEeGfFSseEYpPytEeXXuUUGzjhrRHUulWJNNnNdDnJlLjnjwLtfFTldiYyfRrFOpMtIiYKEWNjJbywWcSsQqiICKUbIiihHIxXpPoOsSdmxGTtCmoklLKZzOQTtrReEqEeuPchjJUVZeRixXtTsmkKiICcrfxrkROoNNnhHrzYEIiDnNdKNnIlHIHdDJjhVvCGgHhXUUcCccTeDdEhIYySLhsSPDwUQqGLEXxevQqVlHfggGfWhHiIwRKkbBrFfkKfBbGgbBQxpPXGgNeUmmXtcXPhHkxXKQNnqjZzBMYVpCFUxXuTbBuTOwWotfFoOLnNUqQPMSfRRNnHuUkKkUVJOXxVQPbBoHhOQqVvYDdtKkTOocgWwGtTtssONPpBwWIrRiQbXxGtuDdzcNQHhqEenwzYMmTtxCvVgfWHyNqQBbzTMmmMdPptnNUtTuqQzplpPuUdsYylifFbBKkwTFftpzqeuvGgxtTEViyOkKdDzZQRsriIoJjMmORSrDkFfrRzZQqeEsdeDTMRkKrmtdMnDdkOoKqyYQNXpPiSsdmZzMDBbuUqxNnXbBnNzZMmoOZzfItEfoOQiIqgGFeUFBCiIcbzZfPpGtTgVvSjivCcVIdDpcCPGxtMVJjPtIQCcqxBCJjcbyYBPpZcCwWzfFrRbjnNJNlLnCUtTuqQMYyKRrhxueEhodDyFfFdvSsxDdXIgGiZpPzzhlfKsBbSkTtFqMmtpFfjQyYqZqQwCdDYyfFcfNnJjFQhDdHuRrUcwEeWYyUusSChUoOeojPpXPpxJOxuUXqbBKEkhvVqhHbXwWPQOohHbcuzXWwBbxnVBbiIvHBbESsNCQqcniNhtTDdRrjJhHHvrRVGpmYyMJjWOowPrRnSsNGmiBkZzkKuUKYtqdDtcFfCqTtQTQbBmYEeBiIEnNebDdEeyeIiMmYosSOylLEBWmMbxXOSPpDdsGglMmLUdeouZGgzTROortEeiEenliIOwWLhgitTIGlLZsSSsQqVvBbplLVYyHhvJQqjFbxEQmkKyVUEeumxXoOZfbBZqQzFkBbKKkzMvohHxVSsvcCXYJvVPoOpQqjvYJjwWrRimMIBszLljjPpbIVhOopdDPcCHdLlcCQqLTtZzOowWnNJjIiRtvhHlLlLzZiJkjJGtTPlLpgUOounNmEeMJjUugGXLksSKSdlLkWQqwKDwDmMdjuOoUnGgNJHsSUmMulkKOorRLfFIiilnGbNnBXxssSmPpChHciIEeDdMOoEZzmMbBLlkKerRWCcckKCTsSgGtwFfwWiYyBsSgGMmbjJIgGUYyuiIeXYyxlHFDdfjHhjLqQsSlpSsPJSsoWwOMmiIOmkjJBbKKUuLlQkKSsmcBbCCVvcnNznNZgsoOVnNvSGfsSrRFwhQqQzZqINnRriHnbMmglZzLWwOobsKoOhHkQqPpTNUzZBYNnycCGkfFKFflqFfQLQqweEKkjJIkKkKWHhwLlJnHhSuUCcjJwTtWQcCTtqsNUuHryQqYRhOokKhQQqqoOStTxHhXwWsSsHRrqvDdCcVQEelLBxWwXbyTtUpIXhHxiPdDxXvVoOfMmFwWWwBbRrDdcCiIUurlIMmiwbPpdOoDBWzqprRPQiIJjjZzwWJZNnZoIihNnHOzhHtRrdLCclfFXKkxDhLJjlTEetHbsSSssSBWVvsbgGsyYSvtZWRlLrwUuziITVBYRruUQqgGiEewWFfIgvixXIVYyBoBbOboOVHqPpcDdCQhvorRcCrRFolLOdDimcgGCMDMmdRryYMvVmvbxXtTzZNGKkgTTSsttsScCfFefFEeIjwcCFSsfLldtFfmMTDeEWJCCcUDdkKimMIzZkKjJKkbNnBbuUBupTtPQCcqZOTtozJhlLHKkNnyYu";


$alphabet = " abcdefghijklmnopqrstuvwxyz";
$alphabet = " ";

$dataafter = $data;
$databefore = null;
//echo $dataafter;
//echo "<br>";

//$datawithouta = dataclean($data,"a");

$datadata = dataCleanClean($data);

//echo $datawithouta;
//echo "<br>";
//echo $datadata;
//echo "<br>";
//echo strlen($datadata);
/*
for ($alph = 0 ;$alph<strlen($alphabet);$alph++){
    $letter = substr($alphabet,$alph,1);

    while ($databefore != $dataafter) {
        $databefore = $dataafter;
        $dataafter = dataClean($databefore);
        //echo "final data--".$dataafter;
        //echo "<br>";
    }

    if ($letter == " "){
        $noletter = $dataafter;
    }

    if (isset($noletter) && !isset($currentlowest)){
        $currentlowest = strlen($dataafter);
    }
    if (strlen($dataafter) < $currentlowest) {
        $currentlowest = strlen($dataafter);
        $currentlowestdata = $dataafter;
        $currentlowestletter = $letter;
    }

    echo $letter . " has a count of " . strlen($dataafter);
    echo "<br>";
    $databefore = null;
    $dataafter = $data;
}

//echo "<br>";
//echo strlen($noletter);
//echo $currentlowest;
//echo "<br>";
//echo $currentlowestletter;

//echo strlen($dataafter);
*/
/*
function dataClean($input,$tocheck = null){
    for ($dataLoop = 0; $dataLoop < strlen($input); $dataLoop++) {
        $searchValue = substr($input,$dataLoop,1);
        $searchValue1 = substr($input,$dataLoop+1,1);
        if (strtoupper($searchValue)!=strtoupper($tocheck)) {
            if (strtoupper($searchValue) == strtoupper($searchValue1)) {
                if ($searchValue != $searchValue1) {
                    $dataLoop = $dataLoop + 1;
                } else {
                    $outputvalue = $outputvalue . $searchValue;
                }
            } else {
                $outputvalue = $outputvalue . $searchValue;
            }
        }
    }
    return $outputvalue;
}


function dataCleanClean($input) {

    $dataafter = $input;
    $databefore = null;
    while ($databefore != $dataafter) {
        for($chunk = 0;$chunk < strlen($dataafter);$chunk++){
            if(substr($dataafter,$chunk,1)!=substr($databefore,$chunk,1)) {
                if ($cleaned = 1) {
                    $dataclean = dataClean(substr($dataafter,$chunk));
                    $databefore = $dataafter;
                    $dataafter = substr($dataafter,0,$chunk). $dataclean;
                    echo "final data--".$dataafter;
                    echo "<br>";
                    $cleaned = 1;
                }
            }
            $cleaned = 0;
        }
        $dataafter = dataClean($dataafter);
    }
    $databefore = null;

    return $dataafter;
}
*/

$REACTING_UNITS = array(
    'aA', 'Aa', 'bB', 'Bb', 'cC', 'Cc', 'dD', 'Dd', 'eE', 'Ee', 'fF', 'Ff', 'gG', 'Gg',
    'hH', 'Hh', 'iI', 'Ii', 'jJ', 'Jj', 'kK', 'Kk', 'lL', 'Ll', 'mM', 'Mm', 'nN', 'Nn',
    'oO', 'Oo', 'pP', 'Pp', 'qQ', 'Qq', 'rR', 'Rr', 'sS', 'Ss', 'tT', 'Tt', 'uU', 'Uu',
    'vV', 'Vv', 'wW', 'Ww', 'xX', 'Xx', 'yY', 'Yy', 'zZ', 'Zz',
);

function reduced_length($polymer,$REACTING_UNITS)
{
    do {
        $polymer = str_replace($REACTING_UNITS, '', $polymer, $count);
    } while ($count > 0);

    return strlen($polymer);
}

$input = $data;

echo reduced_length($input,$REACTING_UNITS);
echo "<br>";
$shortest = PHP_INT_MAX;

foreach (range('a', 'z') as $troublemaker) {
    $test = array($troublemaker, strtoupper($troublemaker));
    $polymer = str_replace($test, '', $input);
    $shortest = min($shortest, reduced_length($polymer,$REACTING_UNITS));
}


//fwrite(STDOUT, $shortest . PHP_EOL);
echo $shortest;


?>
